version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://mukils22it:CXeWTBxsxpczOYzB@cluster0.2j8tn.mongodb.net/LibraryManagementSystem?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=library
    networks:
      - library_network

  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - library_network

networks:
  library_network:
    driver: bridge
